# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('one_time', models.BooleanField(default=False)),
                ('every', models.PositiveSmallIntegerField(default=0, help_text='The message will be sent each N number of minutes', verbose_name='Every')),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
