# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='datetime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='every',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='The message will be sent each N number of minutes', verbose_name='Every'),
        ),
    ]
